apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: expense-tracker
type: Opaque
data:
  # Base64 encoded values (root / ImKundan)
  DATABASE_USERNAME: cm9vdA==
  DATABASE_PASSWORD: SW1LdW5kYW4=
  JWT_SECRET: bXlTdXBlclNlY3JldEtleUZvckpXVFRva2VuR2VuZXJhdGlvbjEyMzQ1Njc4OTA=
