apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: expense-tracker

resources:
  - namespace.yaml
  - mysql-secret.yaml
  - mysql-configmap.yaml
  - mysql-pv.yaml
  - mysql-deployment.yaml
  - backend-secret.yaml
  - backend-configmap.yaml
  - backend-deployment.yaml
  - frontend-configmap.yaml
  - frontend-deployment.yaml
  - ingress.yaml

commonLabels:
  project: expense-tracker
  managed-by: kustomize
