apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: expense-tracker
type: Opaque
data:
  # Base64 encoded values (root / ImKundan)
  mysql-root-password: SW1LdW5kYW4=
  mysql-user: cm9vdA==
  mysql-password: SW1LdW5kYW4=
  mysql-database: ZXhwZW5zZV90cmFja2Vy
